# Dockerイメージにattachして諸々のテストを行う際のbind mountを行う
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: "llvm2kittel:latest"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: .
        target: /opt/llvm2kittel
    command: bash -c "/opt/llvm2kittel/test/build_in_container.sh && bash"
    deploy:
      resources:
        limits:
          memory: 16G
    cap_add:
    - SYS_PTRACE